# Generated by Django 4.1.5 on 2023-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('categoria', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('horario', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=128)),
                ('operacion', models.CharField(max_length=128)),
                ('habitaciones', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('especialidad', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('horario', models.CharField(max_length=128)),
            ],
        ),
    ]
